### ISSUE TITLE
Put up wall to match the approved licensed area.

### ISSUE THREAD

**Issue by chrismcclelland** [teambrewbot/brewbotbelfast#10]
![brewbot-4 xlarge 2x 1424209310](https://cloud.githubusercontent.com/assets/14356/7187997/81b006e0-e46c-11e4-92fd-71115cec48b7.jpg)

**Comment by jonnycampbell** [comment]
![d1c24dfb-33b6-458b-9ed8-893ef9363e9e](https://cloud.githubusercontent.com/assets/333041/7203351/e8ba4af8-e511-11e4-8cbe-6cf92918cdf5.jpeg)
