### ISSUE TITLE
Find office table

### ISSUE THREAD

**Issue by jonnycampbell** [teambrewbot/brewbotbelfast#13]
![brewbot-belfast-12-14-april-2015 medium_large 1429014242](https://cloud.githubusercontent.com/assets/333041/7188138/83e11dae-e46d-11e4-8e8d-c0e8282fb839.jpg)

**Comment by jonnycampbell** [comment]
![brewbotbelfast_2015-apr-16 1](https://cloud.githubusercontent.com/assets/333041/7188147/94703808-e46d-11e4-9068-8e177fcc58d9.jpg)

**Comment by cadwallion** [comment]
This is what a bar is for.
