### ISSUE TITLE
Clean the tap lines.

### ISSUE THREAD

**Issue by chrismcclelland** [teambrewbot/brewbotbelfast#3]
We've 25 taps in the bar, they need a deep cleanse.

**Comment by cadwallion** [comment]
If you've got PBW, heat it to 65C, fill the lines with it, and let it steep overnight.  That'll loosen up the crap in it.  Thorough rinse, then normal beer line cleaner should clean it up.  Otherwise, do a high concentration of alkaline beer cleanser and recirculate 30-40 minutes.
